# Generated by Django 6.0.7 on 2026-08-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedrop',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='filedrop',
            name='expires_hours',
            field=models.IntegerField(choices=[(1, '1 Hour'), (6, '6 Hours'), (24, '24 Hours'), (168, '7 Days')], default=24),
        ),
        migrations.AddField(
            model_name='filedrop',
            name='one_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='filedrop',
            name='original_filename',
            field=models.CharField(default='', max_length=255),
        ),
    ]
