# Generated by Django 6.0.7 on 2026-08-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drop', '0002_filedrop_download_count_filedrop_expires_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedrop',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
