# Generated by Django 6.0.7 on 2026-09-17 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drop', '0004_room_roommessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='drop.roommessage'),
        ),
    ]
