# Generated by Django 6.0.7 on 2026-09-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drop', '0005_roommessage_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommessage',
            name='avatar',
            field=models.CharField(blank=True, default='classic', max_length=30),
        ),
        migrations.AddField(
            model_name='roommessage',
            name='reactions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
