# Generated by Django 6.0.7 on 2026-09-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drop', '0006_roommessage_avatar_roommessage_reactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommessage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roommessage',
            name='is_voice_note',
            field=models.BooleanField(default=False),
        ),
    ]
